"""create table disease

Revision ID: 072e1d25deb9
Revises: 0a2b13c112e5
Create Date: 2024-10-20 11:18:28.358328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072e1d25deb9'
down_revision: Union[str, None] = '0a2b13c112e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom_signature', sa.String(), nullable=False),
    sa.Column('disease_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symptom_signature')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease')
    # ### end Alembic commands ###
