"""Create models identity

Revision ID: 0eec9761c113
Revises: 8456dfced848
Create Date: 2024-08-29 10:54:06.889652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eec9761c113'
down_revision: Union[str, None] = '8456dfced848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_key', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_place', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('sexe', sa.Enum('male', 'female', name='sexe_choices'), nullable=False),
    sa.Column('distinctive_trait', sa.String(length=255), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'rejected', 'done', name='status_choices'), nullable=False),
    sa.Column('father_id', sa.Integer(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['father_id'], ['identity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mother_id'], ['identity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity')
    # ### end Alembic commands ###
