"""Add colum user type

Revision ID: 17d5f45a3d5e
Revises: 95fddebf3b94
Create Date: 2024-10-18 18:12:42.702065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '17d5f45a3d5e'
down_revision: Union[str, None] = '95fddebf3b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_type = postgresql.ENUM('regular', 'doctor', 'admin', name='user_type_choices')
    user_type.create(op.get_bind())
    op.add_column('user', sa.Column('user_type', sa.Enum('regular', 'doctor', 'admin', name='user_type_choices'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    user_type = postgresql.ENUM('regular', 'doctor', 'admin', name='user_type_choices')
    user_type.drop(op.get_bind())
    # ### end Alembic commands ###
