"""update field to medical history

Revision ID: 420ba656a307
Revises: 5699e2df797e
Create Date: 2024-10-21 20:38:58.858077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '420ba656a307'
down_revision: Union[str, None] = '5699e2df797e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    medical_history_status = postgresql.ENUM('in_progress', 'success', 'failed', name='medical_history_status')
    medical_history_status.create(op.get_bind())
    op.add_column('medical_history', sa.Column('status', sa.Enum('in_progress', 'success', 'failed', name='medical_history_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_history', 'status')
    medical_history_status = postgresql.ENUM('in_progress', 'success', 'failed', name='medical_history_status')
    medical_history_status.drop(op.get_bind())
    # ### end Alembic commands ###
