"""Link user and identity

Revision ID: 4595316ff79b
Revises: 17d5f45a3d5e
Create Date: 2024-10-19 09:51:34.727690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4595316ff79b'
down_revision: Union[str, None] = '17d5f45a3d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('identity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'identity', ['identity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'identity_id')
    # ### end Alembic commands ###
