"""Update column

Revision ID: 4f2adc1e1083
Revises: 4595316ff79b
Create Date: 2024-10-19 11:05:27.758119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2adc1e1083'
down_revision: Union[str, None] = '4595316ff79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'identity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'identity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
