"""alter table doctor profile

Revision ID: 77e5e8af7021
Revises: b68f89650dce
Create Date: 2024-10-20 14:07:15.748864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e5e8af7021'
down_revision: Union[str, None] = 'b68f89650dce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profile_keyword_association',
    sa.Column('profil_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.ForeignKeyConstraint(['profil_id'], ['doctor_profile.id'], )
    )
    op.drop_column('doctor_profile', 'keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profile', sa.Column('keywords', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_table('profile_keyword_association')
    op.drop_table('keyword')
    # ### end Alembic commands ###
