"""add field to medical history

Revision ID: 843c5bcba1e7
Revises: cece86ba2cb2
Create Date: 2024-10-21 20:04:59.480678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843c5bcba1e7'
down_revision: Union[str, None] = 'cece86ba2cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_history', sa.Column('disease', sa.String(length=500), nullable=False))
    op.add_column('medical_history', sa.Column('status', sa.String(), nullable=True))
    op.add_column('medical_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_history', 'created_at')
    op.drop_column('medical_history', 'status')
    op.drop_column('medical_history', 'disease')
    # ### end Alembic commands ###
