"""add profile img field

Revision ID: cece86ba2cb2
Revises: e02adcdd139f
Create Date: 2024-10-21 19:05:57.017473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cece86ba2cb2'
down_revision: Union[str, None] = 'e02adcdd139f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity', sa.Column('profile_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity', 'profile_img')
    # ### end Alembic commands ###
