"""cascade on delete

Revision ID: f8a27366ebfa
Revises: 682863ff49ce
Create Date: 2024-10-20 18:16:05.961243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a27366ebfa'
down_revision: Union[str, None] = '682863ff49ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctor_profile_user_id_fkey', 'doctor_profile', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profile_keyword_association_keyword_id_fkey', 'profile_keyword_association', type_='foreignkey')
    op.drop_constraint('profile_keyword_association_profil_id_fkey', 'profile_keyword_association', type_='foreignkey')
    op.create_foreign_key(None, 'profile_keyword_association', 'keyword', ['keyword_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'profile_keyword_association', 'doctor_profile', ['profil_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_identity_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'identity', ['identity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_identity_id_fkey', 'user', 'identity', ['identity_id'], ['id'])
    op.drop_constraint(None, 'profile_keyword_association', type_='foreignkey')
    op.drop_constraint(None, 'profile_keyword_association', type_='foreignkey')
    op.create_foreign_key('profile_keyword_association_profil_id_fkey', 'profile_keyword_association', 'doctor_profile', ['profil_id'], ['id'])
    op.create_foreign_key('profile_keyword_association_keyword_id_fkey', 'profile_keyword_association', 'keyword', ['keyword_id'], ['id'])
    op.drop_constraint(None, 'doctor_profile', type_='foreignkey')
    op.create_foreign_key('doctor_profile_user_id_fkey', 'doctor_profile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
